name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read         # for checkout
  id-token: write        # **critical**: allows GitHub to mint an OIDC token

jobs:
  publish:
    runs-on: ubuntu-latest
    # only needed if you specified an Environment in PyPI
    # environment: pypi     

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build distributions
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish via OIDC
        uses: pypa/gh-action-pypi-publish@v1
        with:
          registry-url: https://upload.pypi.org/legacy/
