name: Python package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to other OS if needed

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Conda using Miniconda (using conda-incubator/setup-miniconda action)
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'  # You can specify a particular version of Miniconda if needed
          auto-update-conda: true      # Ensures Conda is updated to the latest version

      # Step 3: Install dependencies and create the Conda environment
      - name: Create and install Conda environment
        run: |
          conda env update --file environment.yml --name base  # Create or update the environment from environment.yml

      # Step 4: Install dependencies using pip (if needed)
      - name: Install Python dependencies using pip
        run: |
          conda run -n base pip install .  # Install the Python package in the Conda environment

      # Step 5: Set the PYTHONPATH environment variable (if necessary)
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/Prompt_Framework" >> $GITHUB_ENV  # Set PYTHONPATH to the correct folder

      # Step 6: Run tests using pytest (within the Conda environment)
      - name: Run tests with Conda environment
        run: |
          conda run -n base pytest tests/  # Run tests using pytest within the 'base' Conda environment
